spring.application.name=DeserializationViewer
server.port=8087
server.servlet.context-path=/deserialization
env.names=dev,test,product
host.config.windows=C:\\Users\\10534\\Desktop\\hostconfig.properties
host.config.linux=/data/cdp/read_redis/hostconfig.properties
